version: '2'
services:
    agioshipster-app:
        image: agioshipster
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://agioshipster-mysql:3306/agioshipster?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=agioshipster-elasticsearch:9300
        ports:
            - 8080:8080
    agioshipster-mysql:
        extends:
            file: mysql.yml
            service: agioshipster-mysql
    agioshipster-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: agioshipster-elasticsearch
